name: Run All Python Scripts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run all Python files
        run: |
          for pyfile in $(find . -name "*.py" -not -path "./.venv/*"); do
            echo "Running $pyfile"
            python "$pyfile"
          done
