name: Run All Python Scripts (per-file outputs)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || 'main' }}
          persist-credentials: true  # keep GITHUB_TOKEN for push [web:47]

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run each .py and write per-file outputs
        shell: bash
        run: |
          set -eo pipefail
          repo_root="$(pwd)"
          out_root="${repo_root}/outputs"
          mkdir -p "$out_root"
          echo "Repo root: $repo_root"
          echo "Output root: $out_root"
          echo "Python version:"; python --version || python3 --version || true
          while IFS= read -r -d '' pyfile; do
            # Mirror path under outputs/, replace leading ./ if present
            rel="${pyfile#./}"
            out="${out_root}/${rel}.out.md"
            mkdir -p "$(dirname "$out")"
            printf "# Output for %s\n\n" "$rel" > "$out"
            printf "%s\n" '```'
            if command -v python >/dev/null 2>&1; then
              set +e; python "$pyfile" >> "$out" 2>&1; rc=$?; set -e
            else
              set +e; python3 "$pyfile" >> "$out" 2>&1; rc=$?; set -e
            fi
            printf "\n(exit code: %d)\n" "$rc" >> "$out"
            printf "%s\n" '```' >> "$out"
            echo "Wrote $out"
          done < <(find . -type f -name "*.py" -not -path "./.venv/*" -print0)

      - name: Verify generated outputs exist
        shell: bash
        run: |
          echo "git status:"
          git status --porcelain
          echo "find outputs:"
          find outputs -type f -name "*.py.out.md" -print
          echo "Sample content:"
          find outputs -type f -name "*.py.out.md" -print -quit | xargs -r -I{} sh -c 'echo "===" {}; head -n 20 "{}"'

      - name: Stage outputs with git add
        shell: bash
        run: |
          git add outputs/**/*.py.out.md || true
          git status --porcelain

      - name: Commit outputs to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update per-file Python outputs"
          # Use a broad pattern to avoid missing files due to glob differences
          file_pattern: "outputs"
          disable_globbing: true

      - name: Create/update PR with outputs
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update per-file Python outputs"
          title: "Update per-file Python outputs"
          body: "Automated update of outputs/*.py.out.md files."
          branch: ci/update-python-outputs
          base: main
          labels: ci, automation
          add-paths: |
            outputs
